version: "3.9"
services:
  db:
    image: postgres
    restart: always
    container_name: pg
    networks:
      - default
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./database:/var/lib/postgresql
      - ./create_tables.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  # app:
  #   build: app/
  #   restart: always
  #   container_name: app
  #   networks:
  #     - default
  #   ports:
  #     - ${APP_PORT}:${APP_PORT}
  #   volumes:
  #     - ./app:/app
  #   environment:
      # POSTGRES_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}?sslmode=disable"
