version: "3.9"
services:
  # web:
  #   build: data-access
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./database:/database
  db:
    image: postgres
    # command: bash -c "psql -U gkarina_user -d gkarina_database -f /files/create_tables.sql"
    restart: always
    container_name: pg
    networks:
      - default
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql
      - ./postgres/create_tables.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: gkarina_password
      POSTGRES_USER: gkarina_user
      POSTGRES_DB: gkarina_database
