version: "3.9"
services:
  db:
    image: postgres
    restart: always
    container_name: pg
    networks:
      - default
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./postgres:/var/lib/postgresql
      - ./create_tables.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    networks:
      - default
    ports:
      - ${PGADMIN_PORT}:${PGADMIN_LISTEN_PORT}
    volumes:
      - ./pgadmin:/var/lib/pgadmin4
    environment:
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
    depends_on:
      - db
  app:
    build: .
    image: app
    restart: always
    container_name: app
    networks:
      - default
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./app:/app
      - ./run.sh:/run.sh
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
